#!/usr/bin/env python3
"""Generate the exact centered-cell Phase8 code used by the gain observer."""

from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "main/phase8_gain_lut.h"


def phase8(raw: int) -> int:
    q_code, i_code = raw & 15, raw >> 4
    q = (q_code if q_code < 8 else q_code - 16) * 64 + 31.5
    i = (i_code if i_code < 8 else i_code - 16) * 64 + 31.5
    return round(math.atan2(q, i) * 128 / math.pi) & 255


def build() -> str:
    values = [phase8(raw) for raw in range(256)]
    rows = ["    " + ", ".join(f"{value:3d}" for value in values[i:i + 16])
            for i in range(0, 256, 16)]
    return ("#pragma once\n"
            "/* Generated by tools/gen_phase8_gain_lut.py from centered Q4/I4 cells. */\n"
            "static const unsigned char c5vrx_phase8_gain_lut[256] = {\n"
            + ",\n".join(rows) + "\n};\n")


if __name__ == "__main__":
    TARGET.write_text(build(), encoding="utf-8")
    print(f"wrote {TARGET}")
